Software improvements before comp (#61)
* Update fullGateYoloCode.py

* Update fullGateYoloCode.py

* basic modelswitching with oakCams

* added oakd data callback

* small improvement oakd

* small change + refactor

* Update themodele.json

* gate mission

* some experiment with opencv and gate

* tweaks for cvHandler

* Update velocitytracker.py

need to update it so less bulky but am getting an error on line 87 
TypeError: 'float' object is not iterable

* vel tracker

* torpedo mission in progress

* added some mission scripts

* adding small feature for ping360

* Merge

* Missing import statement in ping360

* works on graey? sorta

* color detection for surfacing

* default model

* Torpedo Mission

* small tweaks to disarm and surfacing

* small fixes for torpedo

* naming changes

* Add files via upload

turns the desired heading

* gate mission

* Add files via upload

style points!

* Torpedo corrections

* Formatting

* Formatting

* Error

* adding norm distance for ping360

* refactoring

* Refactoring complete to fire first in open, second in closed

* gate mission restructuring

* camsVersatile can stop and start streams; need ros integration

* camsFix for dynamic cams usage

* small fix

* onyx testing changes

* mavros startup script update

* some more bug fixes and cleanup

* minor changes to the mission stuff

* path and gate

* gate

* fixed cv handler + tested path & gate

* perception stack fixes

* greay pull test

* post pool test cleanup and improvements

* added detctions pipeline

* added model control in debug mode

* doc fixes + setup.py fix

* cams detection pipeline fixes

* bug fixes

* some more small fixes

* Copying template for torpedo 2.0

* model selection add ons

* adjusting logging stuff

* adding testing sonar script

* Updated

* moving dvl and modems around

* cvhandler import fix

* post pool testing commit

* adding depth to keyboard

* adding dummy script handler (example in template)

* adjusting main scripts + adding torpedo

* update from testing

* dvl timestamp

* small fix torpedo

* runyoloongray sample

* dvl integration to robot_control, missing features

* can start camera with model

* path mission changes

* removed raw reset camera

* added buoy and gate model

* path color changes

* added control interface

* added kill for CVhandler--> camsVers

* sorry for multiple pushes; added docs

* readme for using the subs

* gpio testing for graey

* torpedo parameters

* some adjustments for the docs

* torpedo changes

* greaey testing pool

* fix robot control

* **few** changes for the prints stuff, have fun

* repo file formating

* switching to fstrings :)

* added CVhandler being able to init streams from CamsVersatile

* some fixes

* changed buoy model classes

* added error calculation to DVL

* Started buoy code

* added cross lines

* Buoy point detection

* lateral path stuff

* buoy testable

* added traceback

* small fixes for traceback

* Buoy vision works

* fixing traceback (for real)

* gate with heading

* idk what to do for the traceback, it is supposed to work

* ping360 improvements

* graey pool test (buoy + gate)

* Happy birthday Colin and Mabel !✨

* small fixes

* added small keyboard testing for dvl nav

* buoy code changes

* enhanced buoy cv

* buoy testing

* simple dvl nav function and tests

* torpedo rework

* some improvements to pix standalone

* refacto of pix_standalone

* TORPEDO

* adding relative depth to robot_control

* Torpedo

* bug fixes in pix and rc control (mostly pix)

* torp

* torpedo mission using sift keypoint matching

* Comment path cv

* buoy cv changes and model update

* some updates

* some progress on torpedo, working on getting yaw

* pix and bouy fixes

* Add bin cv skeleton

* Update bin cv with TODOs

* new gate logic

* buoy cleanup

* grey updates for softkill

* updated onyx env

* Update bin_cv.py

* Update bin_cv.py

* graey updates

* dvl testing

* oak cams fix (small bug)

* more cams bug fixes, and now no longer need to manually kill cams

* fix robotcontrol

* gate go forward

* compass testing

* surfacing cv update

* jsonifying the .env files

* fix config pix_standalone

* changing relative path for missions

* small cleanup

* small adjustements to surfacing mission

* small fix in bin cv for display

* small change to the threshold

* new gate logic

* new gate mission

* adding ball drop to bin mission + target class

* fixing keyboard control to kill properly

* small adjustment to bin

* added measured offset for the bins

* gate water testing

* path fixing to adjust for cam

* debug stuff for gate'

* update robot control

* adding bins2 model + small refacto of the model selection

* working gate cv from yesterdays test

* dummy data test

* changes to path

* modems api improvements with ACK packets

* removing trash files

* small fix

* small fix

* adding bins3 and bins4, need mappings

* Add files via upload

upload (640, 480) DHD blob file

* Delete 20230728_DHD_openvino_2022.1_6shave.blob

* upload (640, 480) DHD blob file

* pool update

* merge

* updated code

* working calibration script

* works but not tilt compensated

* pool update, will need to debug

* making sure some config is passed to cv and missions

* compass tilt compensated

* improving servos

* small adjustements

* config stuff and bins

* double checking

* tilt compensated heading working

* updated gate logic

* Updated code

* gate code on onyx

* one image aligning gate

* Torpedo Draft

* review torpedo, not finished

* lots of good changes after 2 days of pool testing

---------

Co-authored-by: Parth Saxena <50534120+parth-2007@users.noreply.github.com>
Co-authored-by: Dat-Bois <eeshvij@gmail.com>
Co-authored-by: unknown <saxenaparth007@gmail.com>
Co-authored-by: Mabel Szeto <mabeltreeszeto@gmail.com>
Co-authored-by: ExtraExaByte <55938181+ExtraExaByte@users.noreply.github.com>
Co-authored-by: NoahTang <41347722+NoahTang@users.noreply.github.com>
Co-authored-by: Raymond Song <Raymond.Song98@gmail.com>
Co-authored-by: william14235 <55214793+william14235@users.noreply.github.com>
Co-authored-by: Jui-Yang (Jerry) Hsieh <91396590+jjeerryy@users.noreply.github.com>